# Generated by Django 3.1.2 on 2021-12-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpg',
            name='description',
            field=models.CharField(default='', max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpg',
            name='genre',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
