# Generated by Django 3.1.2 on 2021-12-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211202_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.entity')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stat')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='stat_buffs',
            field=models.ManyToManyField(through='main_app.StatBuff', to='main_app.Stat'),
        ),
    ]
